update the files

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,26 +33,42 @@ jobs:
   deploy:
     needs: build
     runs-on: ubuntu-latest
+    environment: production
 
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
 
     - name: Deploy to EC2
-      uses: appleboy/ssh-action@v0.1.8
-      with:
-        host: ${{ secrets.EC2_HOST }}
-        username: ${{ secrets.EC2_USER }}
-        key: ${{ secrets.EC2_KEY }}
-        port: 22
-        script: |
-          echo "Pulling Docker image from Docker Hub..."
-          docker pull ${{ secrets.DOCKER_USERNAME }}/node:latest
-          echo "Stopping existing container (if any)..."
-          docker stop my-app || true
-          echo "Removing existing container (if any)..."
-          docker rm node || true
-          echo "Starting new container..."
-          docker run -d -p 3333:3333 --name node ${{ secrets.DOCKER_USERNAME }}/node:latest
-        timeout: 20m  # Increase timeout if needed
-        debug: true  # Enable debug logs for troubleshooting
+      env:
+        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
+        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+        IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
+        IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
+      run: |
+        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
+        chmod 400 ~/.ssh/id_rsa
+        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@$EC2_PUBLIC_IP << 'EOF'
+          set -e
+          # Check if Docker is installed and install it if necessary
+          if ! command -v docker &> /dev/null; then
+            sudo yum install -y docker
+            sudo systemctl start docker
+            sudo systemctl enable docker
+            sudo usermod -aG docker $USER
+          fi
+
+          # Cleanup old containers
+          container_ids=$(docker ps -aq)
+          sudo docker stop node || true
+          sudo docker rm node || true
+
+          # Login to Docker Hub
+          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
+
+          # Pull and run the new Docker image
+          docker pull $IMAGE_NAME:$IMAGE_TAG
+          docker run -d --name petclinic -p 3333:3333 $IMAGE_NAME:$IMAGE_TAG
+        EOF
